### ISSUE TITLE
import show error

### ISSUE THREAD

**Issue by zhujin001032** [Hammster/html-element-to-image#3]
<img width="721" alt="image" src="https://user-images.githubusercontent.com/7955640/71962551-a966db80-3234-11ea-9a9b-1b74bbad7e92.png">

**Comment by zhujin001032** [comment]
import NodeToDataURL from 'html-element-to-image';
is OK

**Comment by Hammster** [comment]
Hi this issue is actually still there, i forgot to update the type definition file will do that ASAP

**Comment by Hammster** [comment]
this is now fixed in `2.1.0` please make sure to also use the renamed function `import nodeToDataURL from 'html-element-to-image'` with a lowercase `n`
